// ────────────────────────────────────────────────────────────────────────────
// Opération RÉELLE « 111 rue Gambetta » (Reims) — données issues du planning et
// des marchés N17 (source : 260908 GAMBETTA, réf. ER.T2286). Générée depuis le
// jeu d'injection ; chargeable en un clic depuis « Mes opérations ».
// ────────────────────────────────────────────────────────────────────────────

import type { GanttTask, TaskStatus } from '../types/gantt'
import type { Marche } from './finance'
import type { Reserve } from './reserves'
import type { LotContact, ProjectSeed } from './repo'
import type { ProjectInput } from './projects'
import type { Unit, TaskUnitLink } from './units'
import { weightedProgress } from './rollup'

export const GAMBETTA_PROJECT: ProjectInput = {
  name: '111 rue Gambetta',
  reference: 'ER.T2286',
  address: '111 Rue Gambetta, 51100 Reims',
}

const status = (p: number): TaskStatus => (p >= 100 ? 'completed' : p > 0 ? 'in-progress' : 'not-started')

interface LeafSpec { id: string; title: string; s: string; e: string; dur: number; progress: number }
function leaf(lotId: string, x: LeafSpec): GanttTask {
  return {
    id: x.id, parent_id: `LOT-${lotId}`, lot_id: lotId, title: x.title,
    planned_start: new Date(x.s), planned_end: new Date(x.e), planned_duration: x.dur,
    progress: x.progress, status: status(x.progress),
    priority: 'medium', dependencies: [], is_milestone: false, is_critical: false,
  }
}
function lot(lotId: string, title: string, leaves: GanttTask[]): GanttTask {
  const start = new Date(Math.min(...leaves.map(l => l.planned_start.getTime())))
  const end = new Date(Math.max(...leaves.map(l => l.planned_end.getTime())))
  const progress = weightedProgress(leaves)
  return {
    id: `LOT-${lotId}`, lot_id: lotId, title, planned_start: start, planned_end: end,
    planned_duration: 0, progress, status: 'in-progress', priority: 'medium',
    dependencies: [], is_milestone: false, is_critical: false, children: leaves,
  }
}

const gantt: GanttTask[] = [
  lot('GENERAL', 'Généralités', [
    leaf('GENERAL', { id: 'g-GENERAL-0', title: 'Installation de chantier', s: '2025-11-10', e: '2025-11-16', dur: 5, progress: 100 }),
    leaf('GENERAL', { id: 'g-GENERAL-1', title: 'Réception des travaux', s: '2026-07-27', e: '2026-08-16', dur: 15, progress: 0 }),
  ]),
  lot('LOT01', 'LOT 01 — Démolition / Structure', [
    leaf('LOT01', { id: 'g-LOT01-0', title: 'Curage logement RC Bâtiment C', s: '2025-11-17', e: '2025-11-23', dur: 5, progress: 100 }),
    leaf('LOT01', { id: 'g-LOT01-1', title: 'Démolition du plancher', s: '2025-11-17', e: '2025-12-14', dur: 20, progress: 100 }),
    leaf('LOT01', { id: 'g-LOT01-2', title: 'Reconstitution du plancher', s: '2026-03-09', e: '2026-03-29', dur: 15, progress: 100 }),
  ]),
  lot('LOT02', 'LOT 02 — Couverture', [
    leaf('LOT02', { id: 'g-LOT02-0', title: 'Installations des moyens d\'accès', s: '2025-12-22', e: '2025-12-28', dur: 5, progress: 100 }),
    leaf('LOT02', { id: 'g-LOT02-1', title: 'Bâtiment B', s: '2025-12-22', e: '2026-01-04', dur: 10, progress: 100 }),
    leaf('LOT02', { id: 'g-LOT02-2', title: 'Bâtiment A', s: '2026-02-09', e: '2026-02-22', dur: 10, progress: 100 }),
    leaf('LOT02', { id: 'g-LOT02-3', title: 'Travaux de reprise de charpente', s: '2026-01-19', e: '2026-02-15', dur: 20, progress: 100 }),
    leaf('LOT02', { id: 'g-LOT02-4', title: 'Bâtiment B', s: '2026-01-26', e: '2026-02-15', dur: 15, progress: 100 }),
    leaf('LOT02', { id: 'g-LOT02-5', title: 'Bâtiment A Coté Cour Int.', s: '2026-02-16', e: '2026-03-08', dur: 15, progress: 100 }),
    leaf('LOT02', { id: 'g-LOT02-6', title: 'Bâtiment A Coté Rue', s: '2026-03-23', e: '2026-04-12', dur: 15, progress: 100 }),
    leaf('LOT02', { id: 'g-LOT02-7', title: 'Désenfumage', s: '2026-03-09', e: '2026-03-15', dur: 5, progress: 100 }),
  ]),
  lot('LOT03', 'LOT 03 — Façade / ITE', [
    leaf('LOT03', { id: 'g-LOT03-0', title: 'Installations des moyens d\'accès', s: '2026-01-26', e: '2026-02-08', dur: 10, progress: 100 }),
    leaf('LOT03', { id: 'g-LOT03-1', title: 'Bâtiment C', s: '2026-01-26', e: '2026-02-01', dur: 5, progress: 100 }),
    leaf('LOT03', { id: 'g-LOT03-2', title: 'Bâtiment B', s: '2026-02-02', e: '2026-02-22', dur: 15, progress: 100 }),
    leaf('LOT03', { id: 'g-LOT03-3', title: 'Bâtiment A', s: '2026-02-23', e: '2026-03-01', dur: 5, progress: 100 }),
    leaf('LOT03', { id: 'g-LOT03-4', title: 'Rénovation de façade sur rue', s: '2026-03-02', e: '2026-03-22', dur: 15, progress: 100 }),
    leaf('LOT03', { id: 'g-LOT03-5', title: 'Peinture et lasure', s: '2026-04-13', e: '2026-06-07', dur: 40, progress: 100 }),
    leaf('LOT03', { id: 'g-LOT03-6', title: 'Travaux de finition', s: '2026-05-25', e: '2026-06-14', dur: 15, progress: 100 }),
  ]),
  lot('LOT04', 'LOT 04 — Menuiseries extérieures / serrurerie', [
    leaf('LOT04', { id: 'g-LOT04-0', title: 'Délais de fabrication', s: '2025-12-22', e: '2026-02-08', dur: 35, progress: 100 }),
    leaf('LOT04', { id: 'g-LOT04-1', title: 'Fenêtres PVC', s: '2026-02-09', e: '2026-02-22', dur: 10, progress: 100 }),
    leaf('LOT04', { id: 'g-LOT04-2', title: 'Rénovation des persiennes', s: '2026-03-23', e: '2026-04-05', dur: 10, progress: 100 }),
    leaf('LOT04', { id: 'g-LOT04-3', title: 'Portes d\'entrée extérieure', s: '2026-02-09', e: '2026-02-22', dur: 10, progress: 100 }),
  ]),
  lot('LOT05', 'LOT 05 — Menuiserie intérieure / isolation intérieure', [
    leaf('LOT05', { id: 'g-LOT05-0', title: 'Doublage intérieur', s: '2026-02-16', e: '2026-03-08', dur: 15, progress: 100 }),
    leaf('LOT05', { id: 'g-LOT05-1', title: 'TS Doublage Batiment C RDC', s: '2026-02-16', e: '2026-02-17', dur: 2, progress: 100 }),
    leaf('LOT05', { id: 'g-LOT05-2', title: 'TS Doublage Entrée', s: '2026-09-07', e: '2026-09-08', dur: 2, progress: 0 }),
    leaf('LOT05', { id: 'g-LOT05-3', title: 'Faux-plafonds', s: '2026-03-02', e: '2026-03-15', dur: 10, progress: 0 }),
    leaf('LOT05', { id: 'g-LOT05-4', title: 'Portes SS et portes de rangements', s: '2026-03-16', e: '2026-03-22', dur: 5, progress: 0 }),
    leaf('LOT05', { id: 'g-LOT05-5', title: 'Cloisonnement logement', s: '2026-03-16', e: '2026-03-29', dur: 10, progress: 100 }),
    leaf('LOT05', { id: 'g-LOT05-6', title: 'TS Cloisonnement logement B R+1', s: '2026-09-07', e: '2026-09-08', dur: 2, progress: 0 }),
    leaf('LOT05', { id: 'g-LOT05-7', title: 'Claustra bois (local OM / PAC)', s: '2026-03-30', e: '2026-04-05', dur: 5, progress: 0 }),
    leaf('LOT05', { id: 'g-LOT05-8', title: 'Isolation sous face plancher', s: '2026-04-06', e: '2026-04-19', dur: 10, progress: 0 }),
    leaf('LOT05', { id: 'g-LOT05-9', title: 'Reprise d\'isolation des combles', s: '2026-04-20', e: '2026-04-26', dur: 5, progress: 0 }),
  ]),
  lot('LOT06', 'LOT 06 — Electricité / contrôle d\'accès', [
    leaf('LOT06', { id: 'g-LOT06-0', title: 'Mise en sécurité Elec des logements', s: '2026-03-23', e: '2026-06-14', dur: 60, progress: 50 }),
    leaf('LOT06', { id: 'g-LOT06-1', title: 'Création d\'alimentation pour VR', s: '2026-03-23', e: '2026-06-14', dur: 60, progress: 70 }),
    leaf('LOT06', { id: 'g-LOT06-2', title: 'Passage Fourreau ENEDIS', s: '2026-03-30', e: '2026-04-05', dur: 5, progress: 0 }),
    leaf('LOT06', { id: 'g-LOT06-3', title: 'Travaux de reprises du logement n°5', s: '2026-04-20', e: '2026-05-31', dur: 30, progress: 50 }),
    leaf('LOT06', { id: 'g-LOT06-4', title: 'Alimentations diverses', s: '2026-03-30', e: '2026-06-07', dur: 50, progress: 30 }),
    leaf('LOT06', { id: 'g-LOT06-5', title: 'Eclairage communs et extérieurs', s: '2026-05-18', e: '2026-06-14', dur: 20, progress: 0 }),
    leaf('LOT06', { id: 'g-LOT06-6', title: 'Vidéophonie', s: '2026-06-15', e: '2026-06-28', dur: 10, progress: 0 }),
  ]),
  lot('LOT07', 'LOT 07 — Plomberie / ventilation / chauffage', [
    leaf('LOT07', { id: 'g-LOT07-0', title: 'Travaux de plomberie/sanitaire', s: '2026-03-23', e: '2026-07-19', dur: 85, progress: 60 }),
    leaf('LOT07', { id: 'g-LOT07-1', title: 'Remplacement de ballon ECS', s: '2026-05-04', e: '2026-07-05', dur: 45, progress: 20 }),
    leaf('LOT07', { id: 'g-LOT07-2', title: 'Travaux de ventilation', s: '2026-04-06', e: '2026-06-21', dur: 55, progress: 0 }),
    leaf('LOT07', { id: 'g-LOT07-3', title: 'Travaux de chauffage', s: '2026-04-13', e: '2026-06-07', dur: 40, progress: 0 }),
  ]),
  lot('LOT08', 'LOT 08 — Embellissements', [
    leaf('LOT08', { id: 'g-LOT08-0', title: 'Travaux de peinture interieurs', s: '2026-06-01', e: '2026-07-05', dur: 25, progress: 0 }),
    leaf('LOT08', { id: 'g-LOT08-1', title: 'Travaux de sols souples', s: '2026-06-29', e: '2026-07-26', dur: 20, progress: 0 }),
    leaf('LOT08', { id: 'g-LOT08-2', title: 'Travaux de faience', s: '2026-07-06', e: '2026-07-19', dur: 10, progress: 0 }),
  ]),
]

const lotsConfig: LotContact[] = [
  { id: 'LOT01', name: 'LOT 01 — Démolition / Structure', company: 'LERICHE', contactName: '', email: '', phone: '' },
  { id: 'LOT02', name: 'LOT 02 — Couverture', company: 'BUCZEK', contactName: '', email: '', phone: '' },
  { id: 'LOT03', name: 'LOT 03 — Façade / ITE', company: 'PFC ISOLATION', contactName: '', email: '', phone: '' },
  { id: 'LOT04', name: 'LOT 04 — Menuiseries extérieures / serrurerie', company: 'LA SERRURERIE REMOISE', contactName: '', email: '', phone: '' },
  { id: 'LOT05', name: 'LOT 05 — Menuiserie intérieure / isolation intérieure', company: 'SMP AMENAGEMENT', contactName: '', email: '', phone: '' },
  { id: 'LOT06', name: 'LOT 06 — Electricité / contrôle d\'accès', company: 'SOVECLIM SERVICES', contactName: '', email: '', phone: '' },
  { id: 'LOT07', name: 'LOT 07 — Plomberie / ventilation / chauffage', company: 'SORETHERM', contactName: '', email: '', phone: '' },
  { id: 'LOT08', name: 'LOT 08 — Embellissements', company: 'SMP AMENAGEMENT', contactName: '', email: '', phone: '' },
]

const marches: Marche[] = [
  { id: 'gm-0', lotId: 'LOT01', company: 'LERICHE', amountHT: 12782 },
  { id: 'gm-1', lotId: 'LOT02', company: 'BUCZEK', amountHT: 59158 },
  { id: 'gm-2', lotId: 'LOT03', company: 'PFC ISOLATION', amountHT: 31962 },
  { id: 'gm-3', lotId: 'LOT04', company: 'LA SERRURERIE REMOISE', amountHT: 18851 },
  { id: 'gm-4', lotId: 'LOT05', company: 'SMP AMENAGEMENT', amountHT: 19524 },
  { id: 'gm-5', lotId: 'LOT06', company: 'SOVECLIM SERVICES', amountHT: 59395 },
  { id: 'gm-6', lotId: 'LOT07', company: 'SORETHERM', amountHT: 60000 },
  { id: 'gm-7', lotId: 'LOT08', company: 'SMP AMENAGEMENT', amountHT: 30073 },
]


const reserves: Reserve[] = [
  {
    id: 'reserve-R-001',
    number: 'R-001',
    description: 'MOA indique l\'importance de respecter le format de fichier transmis comme indiqué dans la première page du présent compte rendu.',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'in_progress' as const,
      },
      {
        at: '2026-09-08T00:00:00.000Z',
        visitId: 'cr-n17',
        visitDate: '2026-09-08',
        status: 'done' as const,
        note: '[Fait] MOA indique l\'importance de respecter le format de fichier transmis comme indiqué dans la première page du présent compte rendu.',
      },
    ],
  },
  {
    id: 'reserve-R-002',
    number: 'R-002',
    description: 'Les clés d\'accès au chantier ont été remis à l\'entreprise',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT01'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-003',
    number: 'R-003',
    description: 'Sécurisation de la zone des travaux',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT01'],
    companyIds: ['LERICHE'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-004',
    number: 'R-004',
    description: 'Curage du logement RDC du bâtiment C',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT01'],
    companyIds: ['LERICHE'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-005',
    number: 'R-005',
    description: 'Notes de calcul des IPN et fiches techniques à transmettre',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT01'],
    companyIds: ['LERICHE'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2025-12-09',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-006',
    number: 'R-006',
    description: 'VIGILANCE : Retard important sur la réalisation des travaux',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT01'],
    companyIds: ['LERICHE'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-007',
    number: 'R-007',
    description: 'Sécurisation de la zone des travaux en urgence',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT01'],
    companyIds: ['LERICHE'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2026-02-04',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-008',
    number: 'R-008',
    description: 'Plans et fiches techniques à transmettre en urgence à BCT',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT01'],
    companyIds: ['LERICHE'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2026-02-10',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-009',
    number: 'R-009',
    description: 'Travaux de plancher',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT01'],
    companyIds: ['LERICHE'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2026-02-16',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-010',
    number: 'R-010',
    description: 'Garder la même emprise de l\'ancien plancher. Trappe pour pose échelle à prévoir afin de garder l\'accès à la cave.',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT01'],
    companyIds: ['LERICHE'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2026-02-16',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-011',
    number: 'R-011',
    description: 'Point de vigilance - Retard important',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT01'],
    companyIds: ['LERICHE'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-012',
    number: 'R-012',
    description: 'Remise des clés de chantier',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT01'],
    companyIds: ['LERICHE'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2026-04-30',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-013',
    number: 'R-013',
    description: 'Démarrage travaux de couverture prévu 15/12/2025',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT02'],
    companyIds: ['BUCZEK'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2025-12-15',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'in_progress' as const,
      },
    ],
  },
  {
    id: 'reserve-R-014',
    number: 'R-014',
    description: 'Fin travaux de couverture prévu 13/03/2026',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT02'],
    companyIds: ['BUCZEK'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2026-03-13',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'in_progress' as const,
      },
    ],
  },
  {
    id: 'reserve-R-015',
    number: 'R-015',
    description: '50 % d\'avancement à la date du 23 décembre, cour int. retuilé',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT02'],
    companyIds: ['BUCZEK'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2026-03-13',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-016',
    number: 'R-016',
    description: 'Transmission des documents techniques et délais de désamiantage',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT02'],
    companyIds: ['BUCZEK'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-017',
    number: 'R-017',
    description: 'Transmission fiches techniques tuiles',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT02'],
    companyIds: ['BUCZEK'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-018',
    number: 'R-018',
    description: 'Réunion entre BUCZEK et PFC pour mutualisation des moyens (échafaudages) à programmer',
    priority: 'medium' as const,
    status: 'resolved' as const,
    kind: 'observation' as const,
    lotIds: ['LOT02'],
    companyIds: ['BUCZEK / PFC'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'obsolete' as const,
      },
    ],
  },
  {
    id: 'reserve-R-019',
    number: 'R-019',
    description: 'Pas de mutualisation de moyens. BUCZEK libérera la cour intérieure (bât. B et C) début janvier',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT02'],
    companyIds: ['BUCZEK'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2025-01-16',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
        note: 'Completed: 2026-01-23',
      },
    ],
  },
  {
    id: 'reserve-R-020',
    number: 'R-020',
    description: 'Disjoncteur 10 A à prévoir sur le tableau Elec pour le désenfumage',
    priority: 'high' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT02'],
    companyIds: ['SOVECLIM'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'in_progress' as const,
      },
    ],
  },
  {
    id: 'reserve-R-021',
    number: 'R-021',
    description: 'Emplacement de centrale SSI pour le désenfumage',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT02'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'in_progress' as const,
      },
      {
        at: '2026-09-08T00:00:00.000Z',
        visitId: 'cr-n17',
        visitDate: '2026-09-08',
        status: 'in_progress' as const,
        note: '[PI] Emplacement de centrale SSI pour le désenfumage',
      },
    ],
  },
  {
    id: 'reserve-R-022',
    number: 'R-022',
    description: 'Mutualisation des travaux sur façade principale avec PFC',
    priority: 'high' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT02'],
    companyIds: ['BUCZEK / PFC'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'in_progress' as const,
      },
    ],
  },
  {
    id: 'reserve-R-023',
    number: 'R-023',
    description: 'Fin travaux de couverture côté Rue Gambetta',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT02'],
    companyIds: ['BUCZEK'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2026-04-03',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'in_progress' as const,
      },
    ],
  },
  {
    id: 'reserve-R-024',
    number: 'R-024',
    description: 'Remise des clés de chantier',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT02'],
    companyIds: ['BUCZEK'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2026-04-30',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'in_progress' as const,
      },
      {
        at: '2026-09-08T00:00:00.000Z',
        visitId: 'cr-n17',
        visitDate: '2026-09-08',
        status: 'done' as const,
        note: '[Fait] Remise des clés de chantier',
      },
      {
        at: '2026-09-08T00:00:00.000Z',
        visitId: 'cr-n17',
        visitDate: '2026-09-08',
        status: 'done' as const,
        note: '[Fait] Remise des clés de chantier',
      },
    ],
  },
  {
    id: 'reserve-R-025',
    number: 'R-025',
    description: 'Les clés d\'accès au chantier seront disponibles au siège de Plurial Novilia',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT03'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2025-11-28',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
        note: 'Completed: non récupéré',
      },
    ],
  },
  {
    id: 'reserve-R-026',
    number: 'R-026',
    description: 'Transmission du planning prévisionnel et de délais de commande de matériaux',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT03'],
    companyIds: ['PFC'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2025-12-15',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-027',
    number: 'R-027',
    description: 'Démarrage ITE 05/01/2026 par la cour intérieure',
    priority: 'high' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT03'],
    companyIds: ['PFC'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2025-12-15',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'in_progress' as const,
      },
    ],
  },
  {
    id: 'reserve-R-028',
    number: 'R-028',
    description: 'Dossier EXE à transmettre avant 18/12',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT03'],
    companyIds: ['PFC'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2025-12-18',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'in_progress' as const,
      },
    ],
  },
  {
    id: 'reserve-R-029',
    number: 'R-029',
    description: 'Mise en place des moyens d\'accès',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT03'],
    companyIds: ['PFC'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2026-01-26',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-030',
    number: 'R-030',
    description: 'Démarrage travaux',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT03'],
    companyIds: ['PFC'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2026-02-02',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
        note: 'Completed: 2026-02-02',
      },
    ],
  },
  {
    id: 'reserve-R-031',
    number: 'R-031',
    description: 'Clés récupérées',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT03'],
    companyIds: ['PFC'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-032',
    number: 'R-032',
    description: 'Transmission des documents techniques.',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT03'],
    companyIds: ['PFC'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2025-12-15',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'in_progress' as const,
      },
    ],
  },
  {
    id: 'reserve-R-033',
    number: 'R-033',
    description: 'Réunion entre BUCZEK et PFC pour mutualisation des moyens (échafaudages) à programmer',
    priority: 'medium' as const,
    status: 'resolved' as const,
    kind: 'observation' as const,
    lotIds: ['LOT03'],
    companyIds: ['BUCZEK / PFC'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'obsolete' as const,
      },
    ],
  },
  {
    id: 'reserve-R-034',
    number: 'R-034',
    description: 'Retour tableau isolant ép. 40 donc fini 6 cm',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT03'],
    companyIds: ['PFC'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-035',
    number: 'R-035',
    description: 'VIGILENCE : Retard important sur la réalisation des travaux',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT03'],
    companyIds: ['PFC'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-036',
    number: 'R-036',
    description: 'Mutualisation des travaux sur façade principale avec BUCZEK',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT03'],
    companyIds: ['BUCZEK / PFC'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-037',
    number: 'R-037',
    description: 'Point de vigilance - Nettoyage de zone de stockage cours intérieure.',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT03'],
    companyIds: ['PFC'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2026-03-10',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-038',
    number: 'R-038',
    description: 'Choix de ton de peinture confirmé par le MOA',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT03'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-039',
    number: 'R-039',
    description: 'Nettoyage de façade principale',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT03'],
    companyIds: ['PFC'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2026-03-27',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-040',
    number: 'R-040',
    description: 'Échantillons de peinture pour confirmation par MOA',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT03'],
    companyIds: ['PFC'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2026-03-20',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-041',
    number: 'R-041',
    description: 'Échafaudage et travaux d\'isolation cour A',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT03'],
    companyIds: ['PFC'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2026-03-23',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-042',
    number: 'R-042',
    description: 'Travaux de peinture à réaliser et évacuation de la cour A',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT03'],
    companyIds: ['PFC'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2026-06-16',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-043',
    number: 'R-043',
    description: 'Retard sur les travaux de finition peinture',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT03'],
    companyIds: ['PFC'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2026-06-16',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
      {
        at: '2026-09-08T00:00:00.000Z',
        visitId: 'cr-n17',
        visitDate: '2026-09-08',
        status: 'done' as const,
        note: '[Fait] Retard sur les travaux de finition peinture',
      },
    ],
  },
  {
    id: 'reserve-R-044',
    number: 'R-044',
    description: 'Le local commercial situé au RDC',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT03'],
    companyIds: ['PFC'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2026-06-16',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
      {
        at: '2026-09-08T00:00:00.000Z',
        visitId: 'cr-n17',
        visitDate: '2026-09-08',
        status: 'done' as const,
        note: '[Fait] Le local commercial situé au RDC',
      },
    ],
  },
  {
    id: 'reserve-R-045',
    number: 'R-045',
    description: 'Nettoyage de zone de chantier',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT03'],
    companyIds: ['PFC'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
      {
        at: '2026-09-08T00:00:00.000Z',
        visitId: 'cr-n17',
        visitDate: '2026-09-08',
        status: 'done' as const,
        note: '[Fait] Nettoyage de zone de chantier',
      },
    ],
  },
  {
    id: 'reserve-R-046',
    number: 'R-046',
    description: 'Les clés d\'accès au chantier seront disponibles au siège de Plurial Novilia',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT04'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2025-11-28',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-047',
    number: 'R-047',
    description: 'Transmission du planning prévisionnel et de délais de commande de matériaux',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT04'],
    companyIds: ['SRK'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2025-12-15',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-048',
    number: 'R-048',
    description: 'Délais 1 mois et demi de fabrication et démarrage de lot',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT04'],
    companyIds: ['SRK'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2025-01-31',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-049',
    number: 'R-049',
    description: 'Réception de document PFC',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT04'],
    companyIds: ['PFC'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2025-12-18',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'in_progress' as const,
      },
    ],
  },
  {
    id: 'reserve-R-050',
    number: 'R-050',
    description: 'Transmission des documents techniques.',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT04'],
    companyIds: ['SRK'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2025-12-15',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-051',
    number: 'R-051',
    description: 'Épaisseur et profondeur des retours d\'isolation',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT04'],
    companyIds: ['PFC'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2025-12-15',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-052',
    number: 'R-052',
    description: 'SRK demande des précisions sur la section et largeur des grilles d\'amenée d\'air',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT04'],
    companyIds: ['SORETHER'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2025-12-15',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-053',
    number: 'R-053',
    description: 'SRK demande des précisions sur le côté des installations électriques volets roulants',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT04'],
    companyIds: ['SOVECLIM'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2025-12-15',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-054',
    number: 'R-054',
    description: 'Fabrication en cours',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT04'],
    companyIds: ['SRK'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2026-03-02',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-055',
    number: 'R-055',
    description: 'Pose de menuiserie en cours',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT04'],
    companyIds: ['SRK'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
        note: 'Completed: 2026-03-03',
      },
    ],
  },
  {
    id: 'reserve-R-056',
    number: 'R-056',
    description: 'Pose de bavettes et finition à réaliser',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT04'],
    companyIds: ['SRK'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-057',
    number: 'R-057',
    description: 'Pose des persiennes à réaliser',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT04'],
    companyIds: ['SRK'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
      {
        at: '2026-09-08T00:00:00.000Z',
        visitId: 'cr-n17',
        visitDate: '2026-09-08',
        status: 'done' as const,
        note: '[Fait] Pose des persiennes à réaliser',
      },
    ],
  },
  {
    id: 'reserve-R-058',
    number: 'R-058',
    description: 'Retard sur la finition des bavettes',
    priority: 'medium' as const,
    status: 'resolved' as const,
    kind: 'observation' as const,
    lotIds: ['LOT04'],
    companyIds: ['SRK'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'obsolete' as const,
      },
      {
        at: '2026-09-08T00:00:00.000Z',
        visitId: 'cr-n17',
        visitDate: '2026-09-08',
        status: 'obsolete' as const,
        note: '[Annulé] Retard sur la finition des bavettes',
      },
    ],
  },
  {
    id: 'reserve-R-059',
    number: 'R-059',
    description: 'Finition des bavettes réalisée',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT04'],
    companyIds: ['SRK'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
      {
        at: '2026-09-08T00:00:00.000Z',
        visitId: 'cr-n17',
        visitDate: '2026-09-08',
        status: 'done' as const,
        note: '[Fait] Finition des bavettes réalisée',
      },
    ],
  },
  {
    id: 'reserve-R-060',
    number: 'R-060',
    description: 'Les clés d\'accès au chantier seront disponibles au siège de Plurial Novilia',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT05'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2025-11-28',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-061',
    number: 'R-061',
    description: 'Transmission du planning prévisionnel et de délais de commande de matériaux',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT05'],
    companyIds: ['SMP'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2025-12-15',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-062',
    number: 'R-062',
    description: 'Transmission des documents techniques.',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT05'],
    companyIds: ['SMP'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2025-12-15',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-063',
    number: 'R-063',
    description: 'ITI réalisé',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT05'],
    companyIds: ['SMP'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-064',
    number: 'R-064',
    description: 'Transmission des documents techniques.',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT05'],
    companyIds: ['SMP'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-065',
    number: 'R-065',
    description: 'Sujet de cloisons dégradés suite à la démolition',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT05'],
    companyIds: ['SMP'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'in_progress' as const,
      },
      {
        at: '2026-09-08T00:00:00.000Z',
        visitId: 'cr-n17',
        visitDate: '2026-09-08',
        status: 'in_progress' as const,
        note: '[PI] Sujet de cloisons dégradés suite à la démolition',
      },
    ],
  },
  {
    id: 'reserve-R-066',
    number: 'R-066',
    description: 'Accord pour démol. et reprise du doublage Logement 5 RDC bâtiment C',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT05'],
    companyIds: ['SMP'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-067',
    number: 'R-067',
    description: 'Doublage entrée très endommagé par l\'humidité, avenant pour curage',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT05'],
    companyIds: ['SMP'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'in_progress' as const,
      },
      {
        at: '2026-09-08T00:00:00.000Z',
        visitId: 'cr-n17',
        visitDate: '2026-09-08',
        status: 'in_progress' as const,
        note: 'Doublage entrée très endommagé par l\'humidité, avenant pour curage',
      },
    ],
  },
  {
    id: 'reserve-R-068',
    number: 'R-068',
    description: 'Logement B R+1 - Demande devis pour réaménagement et agrandissement du logement',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT05'],
    companyIds: ['SMP'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'in_progress' as const,
      },
    ],
  },
  {
    id: 'reserve-R-069',
    number: 'R-069',
    description: 'Les clés d\'accès au chantier ont été remis à l\'entreprise',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT06'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
      {
        at: '2026-09-08T00:00:00.000Z',
        visitId: 'cr-n17',
        visitDate: '2026-09-08',
        status: 'done' as const,
        note: '[Fait] Les clés d\'accès au chantier ont été remis à l\'entreprise',
      },
    ],
  },
  {
    id: 'reserve-R-070',
    number: 'R-070',
    description: 'Les clés d\'accès au chantier seront disponibles au siège de Plurial Novilia (Non récupérés)',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT06'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2025-11-28',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
      {
        at: '2026-09-08T00:00:00.000Z',
        visitId: 'cr-n17',
        visitDate: '2026-09-08',
        status: 'done' as const,
        note: '[Fait] Les clés d\'accès au chantier seront disponibles au siège de Plurial Novilia (Non récupérés)',
      },
    ],
  },
  {
    id: 'reserve-R-071',
    number: 'R-071',
    description: 'Installation de l\'éclairage de chantier',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT06'],
    companyIds: ['SOVECLIM'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2025-11-25',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
        note: 'Completed: RETARD',
      },
    ],
  },
  {
    id: 'reserve-R-072',
    number: 'R-072',
    description: 'Transmission des documents techniques.',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT06'],
    companyIds: ['SOVECLIM'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2025-12-15',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-073',
    number: 'R-073',
    description: 'Installation de l\'éclairage de chantier - RELANCE',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT06'],
    companyIds: ['SOVECLIM'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2025-11-25',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
        note: 'Completed: 2025-12-16',
      },
    ],
  },
  {
    id: 'reserve-R-074',
    number: 'R-074',
    description: 'Clé de chantier remise à l\'entreprise',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT06'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
        note: 'Completed: 2026-01-20',
      },
    ],
  },
  {
    id: 'reserve-R-075',
    number: 'R-075',
    description: 'Disjoncteur 10 A à prévoir sur le tableau Elec pour le désenfumage',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT06'],
    companyIds: ['SOVECLIM'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'in_progress' as const,
      },
      {
        at: '2026-09-08T00:00:00.000Z',
        visitId: 'cr-n17',
        visitDate: '2026-09-08',
        status: 'in_progress' as const,
        note: '[PA] Disjoncteur 10 A à prévoir sur le tableau Elec pour le désenfumage',
      },
      {
        at: '2026-09-08T00:00:00.000Z',
        visitId: 'cr-n17',
        visitDate: '2026-09-08',
        status: 'in_progress' as const,
        note: '[PI] Disjoncteur 10 A à prévoir sur le tableau Elec pour le désenfumage',
      },
    ],
  },
  {
    id: 'reserve-R-076',
    number: 'R-076',
    description: 'Passage fourreau pour raccordement ENEDIS',
    priority: 'high' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT06'],
    companyIds: ['SOVECLIM'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'in_progress' as const,
      },
      {
        at: '2026-09-08T00:00:00.000Z',
        visitId: 'cr-n17',
        visitDate: '2026-09-08',
        status: 'in_progress' as const,
        note: '[Rappel] Passage fourreau pour raccordement ENEDIS',
      },
    ],
  },
  {
    id: 'reserve-R-077',
    number: 'R-077',
    description: 'Déplacement des disjoncteurs à l\'intérieur des logements en cours',
    priority: 'high' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT06'],
    companyIds: ['SOVECLIM'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'in_progress' as const,
      },
    ],
  },
  {
    id: 'reserve-R-078',
    number: 'R-078',
    description: 'Retard sur l\'avancement',
    priority: 'high' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT06'],
    companyIds: ['SOVECLIM'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'in_progress' as const,
      },
      {
        at: '2026-09-08T00:00:00.000Z',
        visitId: 'cr-n17',
        visitDate: '2026-09-08',
        status: 'in_progress' as const,
        note: '[Rappel] Retard sur l\'avancement',
      },
    ],
  },
  {
    id: 'reserve-R-079',
    number: 'R-079',
    description: 'Priorité sur la finalisation du bâtiment C',
    priority: 'high' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT06'],
    companyIds: ['SOVECLIM'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'in_progress' as const,
      },
      {
        at: '2026-09-08T00:00:00.000Z',
        visitId: 'cr-n17',
        visitDate: '2026-09-08',
        status: 'in_progress' as const,
        note: '[Rappel] Priorité sur la finalisation du bâtiment C',
      },
    ],
  },
  {
    id: 'reserve-R-080',
    number: 'R-080',
    description: 'Les clés d\'accès au chantier seront disponibles au siège de Plurial Novilia',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT07'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2025-11-28',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'in_progress' as const,
      },
    ],
  },
  {
    id: 'reserve-R-081',
    number: 'R-081',
    description: 'Transmission du planning prévisionnel et de délais de commande de matériaux',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT07'],
    companyIds: ['SORETH.'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2025-12-15',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-082',
    number: 'R-082',
    description: 'Installation de base vie chantier',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT07'],
    companyIds: ['SOVECLIM'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2025-11-25',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'in_progress' as const,
      },
    ],
  },
  {
    id: 'reserve-R-083',
    number: 'R-083',
    description: 'Transmission des documents techniques.',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT07'],
    companyIds: ['SORETH.'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2025-12-15',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-084',
    number: 'R-084',
    description: 'RAPPEL Transmission de documents',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT07'],
    companyIds: ['SORETH.'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2026-02-02',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-085',
    number: 'R-085',
    description: 'Dépose de radiateurs à réaliser',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT07'],
    companyIds: ['SORETH.'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-086',
    number: 'R-086',
    description: 'Devis TS approuvé par le MOA',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT07'],
    companyIds: ['SORETH.'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-087',
    number: 'R-087',
    description: 'Passage des réseaux et des fourreaux au bâtiment C',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT07'],
    companyIds: ['SORETH.'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-088',
    number: 'R-088',
    description: 'Retard Travaux',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT07'],
    companyIds: ['SORETH.'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-089',
    number: 'R-089',
    description: 'Interventions au bâtiment C à démarrer en urgence',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT07'],
    companyIds: ['SORETH.'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'in_progress' as const,
      },
    ],
  },
  {
    id: 'reserve-R-090',
    number: 'R-090',
    description: 'Retard Travaux',
    priority: 'high' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT07'],
    companyIds: ['SORETH.'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'in_progress' as const,
      },
      {
        at: '2026-09-08T00:00:00.000Z',
        visitId: 'cr-n17',
        visitDate: '2026-09-08',
        status: 'done' as const,
        note: '[Fait] Retard Travaux',
      },
      {
        at: '2026-09-08T00:00:00.000Z',
        visitId: 'cr-n17',
        visitDate: '2026-09-08',
        status: 'in_progress' as const,
        note: '[Rappel] Retard Travaux',
      },
    ],
  },
  {
    id: 'reserve-R-091',
    number: 'R-091',
    description: 'Pose de bacs de douches reportée pour fin août',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT07'],
    companyIds: ['SORETH.'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'in_progress' as const,
      },
    ],
  },
  {
    id: 'reserve-R-092',
    number: 'R-092',
    description: 'Pose des compteurs individuels annulée - Malus à prévoir sur la prochaine situation',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT07'],
    companyIds: ['SORETH.'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'in_progress' as const,
      },
      {
        at: '2026-09-08T00:00:00.000Z',
        visitId: 'cr-n17',
        visitDate: '2026-09-08',
        status: 'in_progress' as const,
        note: '[PI] Pose des compteurs individuels annulée - Malus à prévoir sur la prochaine situation',
      },
    ],
  },
  {
    id: 'reserve-R-093',
    number: 'R-093',
    description: 'Les clés d\'accès au chantier seront disponibles au siège de Plurial Novilia',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT08'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2025-11-28',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
      {
        at: '2026-09-08T00:00:00.000Z',
        visitId: 'cr-n17',
        visitDate: '2026-09-08',
        status: 'done' as const,
        note: '[Fait] Les clés d\'accès au chantier seront disponibles au siège de Plurial Novilia',
      },
    ],
  },
  {
    id: 'reserve-R-094',
    number: 'R-094',
    description: 'Transmission du planning prévisionnel et de délais de commande de matériaux',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT08'],
    companyIds: ['SMP'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2025-12-15',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-095',
    number: 'R-095',
    description: 'Transmission des documents techniques.',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT08'],
    companyIds: ['SMP'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    dueDate: '2025-12-15',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'done' as const,
      },
    ],
  },
  {
    id: 'reserve-R-096',
    number: 'R-096',
    description: 'Démarrage de travaux de dépose papier-peints et peinture des 2 logements au bâtiment A',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT08'],
    companyIds: ['SMP'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'in_progress' as const,
      },
    ],
  },
  {
    id: 'reserve-R-097',
    number: 'R-097',
    description: 'Mise en place Claustra local OM',
    priority: 'high' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT08'],
    companyIds: ['SMP'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'in_progress' as const,
      },
      {
        at: '2026-09-08T00:00:00.000Z',
        visitId: 'cr-n17',
        visitDate: '2026-09-08',
        status: 'in_progress' as const,
        note: '[Rappel] Mise en place Claustra local OM',
      },
    ],
  },
  {
    id: 'reserve-R-098',
    number: 'R-098',
    description: 'Peinture partie commune en cours',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT08'],
    companyIds: ['SMP'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'in_progress' as const,
      },
      {
        at: '2026-09-08T00:00:00.000Z',
        visitId: 'cr-n17',
        visitDate: '2026-09-08',
        status: 'in_progress' as const,
        note: 'Peinture partie commune en cours',
      },
    ],
  },
  {
    id: 'reserve-R-099',
    number: 'R-099',
    description: 'Devis TS peinture étages bâtiment C',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT08'],
    companyIds: ['SMP'],
    crNo: 16,
    createdCrNo: 16,
    meetingDate: '2026-08-11',
    follow: [
      {
        at: '2026-08-11T00:00:00.000Z',
        visitId: 'cr-n16',
        visitDate: '2026-08-11',
        status: 'in_progress' as const,
      },
    ],
  },
  {
    id: 'reserve-R-100',
    number: 'R-100',
    description: 'Logement B R+1 - Demande devis pour réamenagement et agrandissement du logement',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT05'],
    companyIds: ['SMP'],
    crNo: 17,
    createdCrNo: 17,
    meetingDate: '2026-09-08',
    follow: [
      {
        at: '2026-09-08T00:00:00.000Z',
        visitId: 'cr-n17',
        visitDate: '2026-09-08',
        status: 'in_progress' as const,
        note: 'Logement B R+1 - Demande devis pour réamenagement et agrandissement du logement',
      },
    ],
  },
  {
    id: 'reserve-R-101',
    number: 'R-101',
    description: 'Interventions au batiment C à démarrer en urgence',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT07'],
    companyIds: ['SORETH.'],
    crNo: 17,
    createdCrNo: 17,
    meetingDate: '2026-09-08',
    follow: [
      {
        at: '2026-09-08T00:00:00.000Z',
        visitId: 'cr-n17',
        visitDate: '2026-09-08',
        status: 'in_progress' as const,
        note: 'Interventions au batiment C à démarrer en urgence',
      },
    ],
  },
  {
    id: 'reserve-R-102',
    number: 'R-102',
    description: 'Démarrage de travaux de dépose papier-peints et peinture des 2 logements au batiment A',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT08'],
    companyIds: ['SMP'],
    crNo: 17,
    createdCrNo: 17,
    meetingDate: '2026-09-08',
    follow: [
      {
        at: '2026-09-08T00:00:00.000Z',
        visitId: 'cr-n17',
        visitDate: '2026-09-08',
        status: 'in_progress' as const,
        note: 'Démarrage de travaux de dépose papier-peints et peinture des 2 logements au batiment A',
      },
    ],
  },
  {
    id: 'reserve-R-103',
    number: 'R-103',
    description: 'Devis TS peinture étages batiment C',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT08'],
    companyIds: ['SMP'],
    crNo: 17,
    createdCrNo: 17,
    meetingDate: '2026-09-08',
    follow: [
      {
        at: '2026-09-08T00:00:00.000Z',
        visitId: 'cr-n17',
        visitDate: '2026-09-08',
        status: 'in_progress' as const,
        note: 'Devis TS peinture étages batiment C',
      },
    ],
  },
  {
    id: 'reserve-R-104',
    number: 'R-104',
    description: 'Lenteur sur les travaux d\'embeillissements.',
    priority: 'medium' as const,
    status: 'open' as const,
    kind: 'observation' as const,
    lotIds: ['LOT08'],
    companyIds: ['SMP'],
    crNo: 17,
    createdCrNo: 17,
    meetingDate: '2026-09-08',
    follow: [
      {
        at: '2026-09-08T00:00:00.000Z',
        visitId: 'cr-n17',
        visitDate: '2026-09-08',
        status: 'in_progress' as const,
        note: 'Lenteur sur les travaux d\'embeillissements.',
      },
    ],
  },
]

]

// ── Bâtiments & zones ────────────────────────────────────────────────────────
//
// Structure réelle transmise pour l'opération (bâtiments A, B, C) :
//   - A et B sont reliés par un même cheminement RDC et desservis par les
//     mêmes escaliers → modélisés comme une circulation commune A/B, rattachée
//     à un troisième « bâtiment » racine dédié (le modèle d'unités ne permet
//     pas d'imbriquer un bâtiment dans un autre — voir lib/units.ts,
//     ALLOWED_CHILDREN — donc pas de duplication de la zone commune par
//     logement, mais pas d'imbrication littérale de A et B non plus).
//   - Bâtiment A : 2 logements, au 2e étage / R+2 uniquement (aucune autre
//     information disponible → aucun autre niveau ni logement créé).
//   - Bâtiment B : 3 logements, un par niveau (RDC, R+1, R+2).
//   - Bâtiment C : indépendant de A/B — créé seul, sans logement inventé :
//     sa structure détaillée reste à compléter depuis les documents source.
// Les identifiants de logement (A-201, A-202, B-001, B-101, B-201) sont des
// identifiants FONCTIONNELS proposés faute de numérotation officielle connue
// à ce stade — à remplacer par les vrais numéros dès qu'ils sont disponibles.
const units: Unit[] = [
  { id: 'u-gambetta-AB', kind: 'building', name: 'A/B — Parties communes', code: 'AB', sortOrder: 0 },
  { id: 'u-gambetta-AB-rdc', parentId: 'u-gambetta-AB', kind: 'level', name: 'RDC', sortOrder: 0 },
  { id: 'u-gambetta-AB-couloir', parentId: 'u-gambetta-AB-rdc', kind: 'common', name: 'Couloir commun RDC', sortOrder: 0 },
  { id: 'u-gambetta-AB-escaliers', parentId: 'u-gambetta-AB', kind: 'common', name: 'Escaliers A/B', sortOrder: 1 },

  { id: 'u-gambetta-A', kind: 'building', name: 'Bâtiment A', code: 'A', sortOrder: 1 },
  { id: 'u-gambetta-A-r2', parentId: 'u-gambetta-A', kind: 'level', name: 'R+2', sortOrder: 0 },
  { id: 'u-gambetta-A-201', parentId: 'u-gambetta-A-r2', kind: 'dwelling', name: 'Logement A-201', code: 'A-201', sortOrder: 0 },
  { id: 'u-gambetta-A-202', parentId: 'u-gambetta-A-r2', kind: 'dwelling', name: 'Logement A-202', code: 'A-202', sortOrder: 1 },

  { id: 'u-gambetta-B', kind: 'building', name: 'Bâtiment B', code: 'B', sortOrder: 2 },
  { id: 'u-gambetta-B-rdc', parentId: 'u-gambetta-B', kind: 'level', name: 'RDC', sortOrder: 0 },
  { id: 'u-gambetta-B-001', parentId: 'u-gambetta-B-rdc', kind: 'dwelling', name: 'Logement B-001', code: 'B-001', sortOrder: 0 },
  { id: 'u-gambetta-B-r1', parentId: 'u-gambetta-B', kind: 'level', name: 'R+1', sortOrder: 1 },
  { id: 'u-gambetta-B-101', parentId: 'u-gambetta-B-r1', kind: 'dwelling', name: 'Logement B-101', code: 'B-101', sortOrder: 0 },
  { id: 'u-gambetta-B-r2', parentId: 'u-gambetta-B', kind: 'level', name: 'R+2', sortOrder: 2 },
  { id: 'u-gambetta-B-201', parentId: 'u-gambetta-B-r2', kind: 'dwelling', name: 'Logement B-201', code: 'B-201', sortOrder: 0 },

  // Indépendant de A/B — structure détaillée non disponible : pas de niveau
  // ni de logement inventé, uniquement le bâtiment lui-même.
  { id: 'u-gambetta-C', kind: 'building', name: 'Bâtiment C', code: 'C', sortOrder: 3 },
]

// Rattachements tâche ↔ unité : uniquement les tâches dont le TITRE nomme
// explicitement un bâtiment dans les données source (aucune tâche n'est
// devinée ou déplacée vers un logement précis, faute de source le confirmant).
// Rattacher au bâtiment vaut pour tout ce qu'il contient (voir
// taskConcernsUnit, lib/units.ts) : ces tâches apparaîtront donc dans chacun
// des logements du bâtiment concerné pendant une visite.
const taskUnits: TaskUnitLink[] = [
  { taskId: 'g-LOT01-0', unitId: 'u-gambetta-C' },   // « Curage logement RC Bâtiment C »
  { taskId: 'g-LOT02-1', unitId: 'u-gambetta-B' },   // « Bâtiment B »
  { taskId: 'g-LOT02-2', unitId: 'u-gambetta-A' },   // « Bâtiment A »
  { taskId: 'g-LOT02-4', unitId: 'u-gambetta-B' },   // « Bâtiment B »
  { taskId: 'g-LOT02-5', unitId: 'u-gambetta-A' },   // « Bâtiment A Coté Cour Int. »
  { taskId: 'g-LOT02-6', unitId: 'u-gambetta-A' },   // « Bâtiment A Coté Rue »
  { taskId: 'g-LOT03-1', unitId: 'u-gambetta-C' },   // « Bâtiment C »
  { taskId: 'g-LOT03-2', unitId: 'u-gambetta-B' },   // « Bâtiment B »
  { taskId: 'g-LOT03-3', unitId: 'u-gambetta-A' },   // « Bâtiment A »
]

/** Toutes les tranches de l'opération Gambetta, prêtes pour seedProjectData(). */
export function buildGambettaSeed(): ProjectSeed {
  return { gantt, lotsConfig, marches, reserves, units, taskUnits }
}
