import { useState, type FormEvent } from 'react'
import { addCompany, addLot, addUnit, setAssignment } from '../lib/data'
import { DpgfImport } from './DpgfImport'
import type { Company, Lot, Unit, UnitKind } from '../lib/types'

type Props = { operationId: string; units: Unit[]; lots: Lot[]; companies: Company[]; assignments: { lot_id: string; unit_id: string | null; scope: string }[]; reload: () => Promise<void> }
const labels: Record<UnitKind, string> = { building: 'Bâtiment', dwelling: 'Logement', common_area: 'Partie commune', exterior: 'Extérieur', zone: 'Zone' }
export function Administration({ operationId, units, lots, companies, assignments, reload }: Props) {
  const [kind, setKind] = useState<UnitKind>('building'); const [message, setMessage] = useState<string | null>(null)
  const submit = (action: () => Promise<void>) => async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); try { await action(); await reload(); setMessage('Enregistré.'); event.currentTarget.reset() } catch (e) { setMessage(e instanceof Error ? e.message : 'Erreur.') } }
  const dwellings = units.filter((unit) => unit.kind === 'dwelling')
  return <section className="stack"><h2>Administration</h2>{message && <p className="notice">{message}</p>}
    <details open><summary>Sites et localisations</summary><form onSubmit={submit(async () => { const form = new FormData(document.querySelector('#unit-form') as HTMLFormElement); await addUnit(operationId, { kind, code: String(form.get('code') || '') || null, name: String(form.get('name')), floor: String(form.get('floor') || '') || null, parent_id: String(form.get('parent') || '') || null, sort_order: Number(form.get('order') || 0) }) })} id="unit-form" className="form-grid"><select value={kind} onChange={(e) => setKind(e.target.value as UnitKind)}>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><input name="code" placeholder="Code / numéro"/><input required name="name" placeholder="Nom"/><input name="floor" placeholder="Étage"/><select name="parent"><option value="">Sans parent</option>{units.filter((u) => u.kind === 'building').map((u) => <option key={u.id} value={u.id}>{u.name}</option>)}</select><input name="order" type="number" placeholder="Ordre"/><button>Ajouter</button></form><List title="Éléments configurés" items={units.map((u) => `${labels[u.kind]} · ${u.code ?? ''} ${u.name}`)} /></details>
    <details><summary>Entreprises</summary><form onSubmit={submit(async () => { const f = new FormData(document.querySelector('#company-form') as HTMLFormElement); await addCompany(operationId, { name: String(f.get('name')), contact_name: String(f.get('contact') || '') || null, email: String(f.get('email') || '') || null, phone: String(f.get('phone') || '') || null }) })} id="company-form" className="form-grid"><input required name="name" placeholder="Entreprise"/><input name="contact" placeholder="Contact"/><input name="email" type="email" placeholder="E-mail"/><input name="phone" placeholder="Téléphone"/><button>Ajouter</button></form><List title="Entreprises" items={companies.map((c) => `${c.name}${c.contact_name ? ` · ${c.contact_name}` : ''}`)} /></details>
    <details><summary>Lots</summary><form onSubmit={submit(async () => { const f = new FormData(document.querySelector('#lot-form') as HTMLFormElement); await addLot(operationId, { number: String(f.get('number') || '') || null, name: String(f.get('name')), company_id: String(f.get('company') || '') || null, sort_order: Number(f.get('order') || 0) }) })} id="lot-form" className="form-grid"><input name="number" placeholder="Numéro"/><input required name="name" placeholder="Intitulé"/><select name="company"><option value="">Sans entreprise</option>{companies.map((c) => <option value={c.id} key={c.id}>{c.name}</option>)}</select><input name="order" type="number" placeholder="Ordre"/><button>Ajouter</button></form><List title="Lots" items={lots.map((l) => `${l.number ?? l.code ?? ''} · ${l.name}`)} /></details>
    <details><summary>Bâtiment → logements → lots</summary>{dwellings.length === 0 ? <p>Créez d’abord les bâtiments et logements.</p> : dwellings.map((dwelling) => <fieldset key={dwelling.id}><legend>{dwelling.code ?? dwelling.name}</legend>{lots.map((lot) => { const checked = assignments.some((a) => a.lot_id === lot.id && a.unit_id === dwelling.id); return <label className="check" key={lot.id}><input type="checkbox" checked={checked} onChange={async (e) => { await setAssignment(operationId, lot.id, dwelling.id, 'dwelling', e.target.checked); await reload() }}/>{lot.number ?? lot.code} {lot.name}</label> })}</fieldset>)}</details>
    <DpgfImport operationId={operationId} onDone={reload}/></section>
}
function List({ title, items }: { title: string; items: string[] }) { return <div><h3>{title}</h3>{items.length ? <ul>{items.map((item, index) => <li key={`${item}-${index}`}>{item}</li>)}</ul> : <p>Aucun élément.</p>}</div> }
