import { useState } from 'react'
import * as XLSX from 'xlsx'
import { supabase } from '../lib/supabase'

type Row = Record<string, unknown>
type Props = { operationId: string; onDone: () => Promise<void> }
const fields = ['lot', 'section', 'reference', 'designation', 'unit', 'quantity', 'unit_price', 'amount'] as const
export function DpgfImport({ operationId, onDone }: Props) {
  const [fileName, setFileName] = useState(''); const [sheet, setSheet] = useState(''); const [rows, setRows] = useState<Row[]>([]); const [columns, setColumns] = useState<string[]>([]); const [mapping, setMapping] = useState<Record<string, string>>({}); const [message, setMessage] = useState('')
  async function analyze(file: File) { const workbook = XLSX.read(await file.arrayBuffer(), { type: 'array' }); const sheetName = workbook.SheetNames[0]; const raw = XLSX.utils.sheet_to_json<Row>(workbook.Sheets[sheetName], { defval: '' }); const keys = Object.keys(raw[0] ?? {}); setFileName(file.name); setSheet(sheetName); setRows(raw); setColumns(keys); setMapping(Object.fromEntries(fields.map((field) => [field, keys.find((key) => key.toLowerCase().includes(field.replace('_', ''))) ?? '']))); setMessage(`${raw.length} lignes analysées dans « ${sheetName} ».`) }
  async function importRows() { if (!supabase) return; const required = ['lot', 'designation']; if (required.some((field) => !mapping[field])) { setMessage('Associez au minimum Lot et Désignation.'); return } try { const { error: importError } = await supabase.from('dpgf_imports').insert({ operation_id: operationId, filename: fileName, column_mapping: mapping }); if (importError) throw importError; const lots = new Map<string, string>(); for (const [index, row] of rows.entries()) { const lotName = String(row[mapping.lot] ?? '').trim(); const designation = String(row[mapping.designation] ?? '').trim(); if (!lotName || !designation) continue; if (!lots.has(lotName)) { const { data, error } = await supabase.from('lots').insert({ operation_id: operationId, name: lotName, number: lotName }).select('id').single(); if (error) throw error; lots.set(lotName, data.id) } const reference = mapping.reference ? String(row[mapping.reference] ?? '') || null : null; const { error } = await supabase.from('tasks').insert({ operation_id: operationId, lot_id: lots.get(lotName), section: mapping.section ? String(row[mapping.section] ?? '') || null : null, reference, source_reference: reference, source_sheet: sheet, source_row: index + 2, name: designation, unit: mapping.unit ? String(row[mapping.unit] ?? '') || null : null, quantity: mapping.quantity ? Number(row[mapping.quantity]) || null : null, unit_price: mapping.unit_price ? Number(row[mapping.unit_price]) || null : null, amount: mapping.amount ? Number(row[mapping.amount]) || null : null, sort_order: index }); if (error) throw error } await onDone(); setMessage('Import DPGF terminé.') } catch (e) { setMessage(e instanceof Error ? e.message : 'Import impossible.') } }
  return <details><summary>Importer DPGF</summary><p>Sélection → analyse → correspondance → prévisualisation → import. Aucun contenu n’est créé avant validation.</p><input type="file" accept=".xlsx,.xls" onChange={(e) => e.target.files?.[0] && void analyze(e.target.files[0])}/>{message && <p className="notice">{message}</p>}{columns.length > 0 && <><div className="form-grid">{fields.map((field) => <label key={field}>{field}<select value={mapping[field] ?? ''} onChange={(e) => setMapping({ ...mapping, [field]: e.target.value })}><option value="">Non importé</option>{columns.map((column) => <option value={column} key={column}>{column}</option>)}</select></label>)}</div><div className="preview"><strong>Prévisualisation ({Math.min(rows.length, 10)} lignes)</strong><pre>{JSON.stringify(rows.slice(0, 10), null, 2)}</pre></div><button onClick={() => void importRows()}>Valider et importer</button></>}</details>
}
