import { useState } from 'react'
import * as XLSX from 'xlsx'
import { supabase } from '../lib/supabase'

type Row = Record<string, unknown>
type Props = { operationId: string; onDone: () => Promise<void> }
const fields = ['lot', 'section', 'reference', 'designation', 'unit', 'quantity', 'unit_price', 'amount'] as const
export function DpgfImport({ operationId, onDone }: Props) {
  const [filename, setFilename] = useState(''); const [sheet, setSheet] = useState(''); const [rows, setRows] = useState<Row[]>([]); const [columns, setColumns] = useState<string[]>([]); const [mapping, setMapping] = useState<Record<string, string>>({}); const [message, setMessage] = useState('')
  async function analyze(file: File) { const workbook = XLSX.read(await file.arrayBuffer(), { type: 'array' }); const sheetName = workbook.SheetNames[0]; const values = XLSX.utils.sheet_to_json<Row>(workbook.Sheets[sheetName], { defval: '' }); const headers = Object.keys(values[0] ?? {}); setFilename(file.name); setSheet(sheetName); setRows(values); setColumns(headers); setMapping(Object.fromEntries(fields.map((field) => [field, headers.find((header) => header.toLowerCase().includes(field.replace('_', ''))) ?? '']))); setMessage(`${values.length} lignes analysées. Vérifiez la correspondance avant import.`) }
  async function importRows() { if (!supabase) return; if (!mapping.lot || !mapping.designation) { setMessage('Les colonnes Lot et Désignation sont obligatoires.'); return } try { const { data: imported, error: importError } = await supabase.from('dpgf_imports').insert({ operation_id: operationId, filename, column_mapping: mapping }).select('id').single(); if (importError) throw importError; const lots = new Map<string, string>(); for (const [index, row] of rows.entries()) { const lotName = String(row[mapping.lot] ?? '').trim(); const designation = String(row[mapping.designation] ?? '').trim(); if (!lotName || !designation) continue; if (!lots.has(lotName)) { const { data, error } = await supabase.from('lots').insert({ operation_id: operationId, number: lotName, name: lotName }).select('id').single(); if (error) throw error; lots.set(lotName, data.id) } const reference = mapping.reference ? String(row[mapping.reference] ?? '') || null : null; const { error } = await supabase.from('tasks').insert({ operation_id: operationId, lot_id: lots.get(lotName), import_id: imported.id, source_sheet: sheet, source_row: index + 2, source_reference: reference, reference, section: mapping.section ? String(row[mapping.section] ?? '') || null : null, name: designation, unit: mapping.unit ? String(row[mapping.unit] ?? '') || null : null, quantity: mapping.quantity ? Number(row[mapping.quantity]) || null : null, unit_price: mapping.unit_price ? Number(row[mapping.unit_price]) || null : null, amount: mapping.amount ? Number(row[mapping.amount]) || null : null, sort_order: index }); if (error) throw error } await onDone(); setMessage('Import terminé.') } catch (error) { setMessage(error instanceof Error ? error.message : 'Import impossible.') } }
  return <details><summary>Importer DPGF</summary><p>Sélection → analyse → correspondance → aperçu → validation. Aucune ligne n’est créée avant validation.</p><input type="file" accept=".xls,.xlsx" onChange={(event) => event.target.files?.[0] && void analyze(event.target.files[0])}/>{message && <p className="notice">{message}</p>}{columns.length > 0 && <><div className="form-grid">{fields.map((field) => <label key={field}>{field}<select value={mapping[field] ?? ''} onChange={(event) => setMapping({ ...mapping, [field]: event.target.value })}><option value="">Non importé</option>{columns.map((column) => <option key={column} value={column}>{column}</option>)}</select></label>)}</div><pre className="preview">{JSON.stringify(rows.slice(0, 10), null, 2)}</pre><button type="button" onClick={() => void importRows()}>Valider et importer</button></>}</details>
}
