import { useMemo, useState, type FormEvent } from 'react'
import { addProgress, effectiveAssignments, startVisit } from '../lib/data'
import type { Lot, Unit } from '../lib/types'
type Props = { operationId: string; units: Unit[]; lots: Lot[]; assignments: { lot_id: string; unit_id: string | null; scope: string }[] }
export function VisitForm({ operationId, units, lots, assignments }: Props) {
 const [unitId, setUnitId] = useState(''); const [message, setMessage] = useState<string | null>(null); const [effective, setEffective] = useState<{ lot_id: string; enabled: boolean; source: 'specific' | 'inherited' }[]>([]); const applicable = useMemo(() => lots.filter((lot) => effective.length ? effective.some((assignment) => assignment.lot_id === lot.id && assignment.enabled) : assignments.some((assignment) => assignment.lot_id === lot.id && assignment.unit_id === unitId)), [assignments, lots, unitId, effective])
 async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); try { const visit = await startVisit(operationId, { title: String(f.get('title') || '') || null, note: String(f.get('note') || '') || null }); const lotId = String(f.get('lot')); if (lotId) await addProgress(operationId, visit.id, unitId || null, lotId, null, f.get('percentage') ? Number(f.get('percentage')) : null, String(f.get('status')), String(f.get('comment') || '')); setMessage('Visite et saisie d’avancement enregistrées dans l’historique.'); e.currentTarget.reset() } catch (err) { setMessage(err instanceof Error ? err.message : 'Erreur.') } }
 return <section className="stack"><h2>Démarrer la visite</h2><p>Chaque validation crée une visite et une ligne d’historique d’avancement.</p>{message && <p className="notice">{message}</p>}<form className="form-grid" onSubmit={submit}><input name="title" placeholder="Objet de la visite"/><select value={unitId} onChange={(event) => { const id = event.target.value; setUnitId(id); if (id) void effectiveAssignments(id).then(setEffective).catch((error: Error) => setMessage(error.message)); else setEffective([]) }}><option value="">Localisation</option>{units.map((unit) => <option value={unit.id} key={unit.id}>{unit.code ?? ''} {unit.name}</option>)}</select><select name="lot"><option value="">Lot applicable</option>{applicable.map((lot) => { const source = effective.find((assignment) => assignment.lot_id === lot.id)?.source; return <option value={lot.id} key={lot.id}>{lot.number ?? lot.code} {lot.name}{source ? ` — ${source === 'inherited' ? 'HÉRITÉ' : 'SPÉCIFIQUE'}` : ''}</option> })}</select><input name="percentage" type="number" min="0" max="100" placeholder="Avancement %"/><select name="status"><option value="new">Nouveau</option><option value="not_started">Pas encore</option><option value="reminder">Rappel</option><option value="blocked">Bloqué</option><option value="done">Fait</option><option value="not_applicable">N/C</option></select><textarea name="comment" placeholder="Note d’avancement"/><textarea name="note" placeholder="Note générale de visite"/><button>Enregistrer la visite</button></form></section>
}
